### ISSUE TITLE
Build warning

### ISSUE THREAD

**Issue by 0323pin** [domenukk/quarto_rs#1]
Hi,

You're most probably already aware of this but, building `quarto` generates the following warning:

```
===> Building for quarto-0.2.0
   Compiling quarto v0.2.0 (/usr/pkgsrc/wip/quarto/work/quarto-0.2.0)
warning: lint `const_err` has been removed: converted into hard error, see issue #71800 <https://github.com/rust-lang/rust/issues/71800> for more information
  --> src/main.rs:34:9
   |
34 |         const_err,
   |         ^^^^^^^^^
   |
   = note: `#[warn(renamed_and_removed_lints)]` on by default

warning: `quarto` (bin "quarto") generated 1 warning
    Finished release [optimized] target(s) in 3.78s
```

OS: NetBSD 10.99.7
Rust: 1.71.1

Regards

**Comment by 0323pin** [comment]
FYI, I've created a package for NetBSD and have merged it into the main branch. Commit message for reference, https://mail-index.netbsd.org/pkgsrc-changes/2023/08/12/msg280601.html

**Comment by domenukk** [comment]
Thank you. Didn't see the warning on my end but removed the `const_err` deny nevertheless. :) (see #2)
And thanks for creating the netbsd package :)

**Comment by 0323pin** [comment]
> And thanks for creating the netbsd package

Let me know if you would like install instructions on README.MD, I can do a PR for it.

**Comment by domenukk** [comment]
Up to you ;)
